### ISSUE TITLE
TypeError around _reactSizes2.default not being a function

### ISSUE THREAD

**Issue by bjankord** [renatorib/react-sizes#20]
We just started getting test failures with the following error message:

`TypeError: (0 , _reactSizes2.default) is not a function`.

We are using react-bps in our code base.

**Comment by bjankord** [comment]
I believe this is caused by the changes to how `withSizes` is exported in `src/index.js` from this commit: https://github.com/renatorib/react-sizes/commit/0840d61cb7681abcd3f8641dadf7d498a0131f6f

There are likely some changes needed in react-bps in how it imports `withSizes` to fix this.

**Comment by renatorib** [comment]
Thanks (and sorry) @bjankord I'll take a look on it tonight

For now you can use the version `0.3.1`

**Comment by renatorib** [comment]
Confirmed.

`0.3.2` has a breaking change (my bad, sorry).
I'm publishing a `0.3.3` patch to fix this.

**Comment by renatorib** [comment]
@bjankord is everything okay?

I will close this issue. If the problem persist to you, please comment here.
Thanks
