### ISSUE TITLE
Question: why not media query listeners?

### ISSUE THREAD

**Issue by PerfectPixel** [renatorib/react-sizes#24]
I was reading your medium post and wondered why you were not using media queries listeners instead of listening to the resize event?

```
var mediaQueryList = window.matchMedia("(max-width: 480px)");
mediaQueryList.addListener(function(mq) {
  console.log(mq.matches);
});
```

Would print `true` or `false` to the console once the media query match changes. No event throttling or debouncing needed as you only receive an event if the match changes (matches -> does not match and vice versa).

https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Testing_media_queries#Receiving_query_notifications

Maybe I am missing a down-side of this approach so I am interested in your take.

Thanks!

**Comment by renatorib** [comment]
Yes, I know matchMedia. For many times I thought of refactoring the react-sizes using it, but I believe that the way it is, it serves the purpose very well.

A great benefit of working only with two number values (width / height) is that I can make simple checks without the need to create media query strings with max/min width, etc. And is also simple to make fallback in the case of SSR (with fallback/mock values: https://github.com/renatorib/react-sizes#server-side-rendering)

I still think about creating another improved lib using matchMedia. But for now I do not feel this need. I use react-sizes in my work and feel that it fits very well to my needs without any kind of problem. Not even performance.

However, thanks for the tips 😄

**Comment by PerfectPixel** [comment]
cool, thanks for the input. Using numeric values and not generate strings makes ramp-up easier. I guess every solution has its drawbacks.

**Comment by renatorib** [comment]
😄
