### ISSUE TITLE
Version 1.0.0 install not working

### ISSUE THREAD

**Issue by alexpricedev** [renatorib/react-sizes#25]
Hey! Thanks for the 1.0.0 update. Unfortunately I get a `not-found` error for `react-sizes`. It seems like the `es` and `dist` directories aren't getting published to NPM. I've installed from a personal fork for now (with the compiled responses checked in [😱]) but if you could publish the compete build that would be awesome!

**Comment by renatorib** [comment]
🤔 It's weird. I'll check this! Thanks

**Comment by michelemazzucco** [comment]
Same issue here, can you check the files published on npm registry? Thanks a lot 👍

**Comment by renatorib** [comment]
@alexpriceonline @michelemazzucco 
It's not publishing `es` folder. I'll fix it and publish a new patch version.

Sorry for that!

**Comment by renatorib** [comment]
I've published version `1.0.2`. Can you guys test? Thanks!

**Comment by michelemazzucco** [comment]
@renatorib thank you so much! Probably I've found another bug related to SSR. In the next few days I'll make more test.
