### ISSUE TITLE
Bug: throttle can't be configured due to an error in the code

### ISSUE THREAD

**Issue by ghost** [renatorib/react-sizes#27]
Hi, 

great library. I was playing around with it and found a bug. You use lodash.throttle to slow down how often react rerenders when the browser changes. You made it "possible" to configure this value using the `SizesProvider` component. This however does not work. Because the logic is expecting this value on `this.context.throttle`. The `SizesProvider` however stores it in a dict with the key `_ReactSizesConfig_`. 

The line ~57 in `withSizes.js` should be 

```
throttledDispatchSizes = throttle(
      this.dispatchSizes,
      (this.context[contextKey] || {}).throttle || 200
    )
```
and not:

```
throttledDispatchSizes = throttle(
     this.dispatchSizes,
     this.context.throttle || 200
)
```

**Comment by renatorib** [comment]
Thanks!

**Comment by ghost** [comment]
Great thanks for publishing.
